class ValidationError(Exception):
    pass

class NetworkError(Exception):
    pass
